name = "geo_coords"
description = "Geo coordinates calculation for determining Location, Distance, Bearing"
version = "1.0.0"

authors = ["Saiffullah Sabir Mohamed"]
maintainers = ["Saiffullah Sabir Mohamed <saif25596@outlook.com>"]
maintainers-logins = ["TechnicalVillager"]

licenses = "MIT"
tags = ["geo", "coordinates", "latitude", "longitude", "distance", "bearing", "haversine"]
website = ""
