name = "geo_coords_calculation"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Saiffullah Sabir Mohamed"]
maintainers = ["Saiffullah Sabir Mohamed <saif25596@outlook.com>"]
maintainers-logins = ["TechnicalVillager"]

executables = ["geo_coords_calculation"]

[[depends-on]]
geo_coords = "*"

[[pins]]
geo_coords = { path = "../../" }